// settings
export const PAGES_CHANGE_ACTIVE = "PAGES_CHANGE_ACTIVE";

// charts
export const CHARTS_CHANGE_PUBLICATIONS_TYPE = "CHARTS_CHANGE_PUBLICATIONS_TYPE";
export const CHARTS_CHANGE_CITATIONS_TYPE = "CHARTS_CHANGE_CITATIONS_TYPE";

export const CHARTS_CHANGE_RANGE = "CHARTS_CHANGE_RANGE";

export const CHARTS_CHANGE_DATA = "CHARTS_CHANGE_DATA";

